//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJStudio.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HJStudioEntities : DbContext
    {
        public HJStudioEntities()
            : base("name=HJStudioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalenderEvent> CalenderEvents { get; set; }
        public virtual DbSet<EmployeeQuotationDay> EmployeeQuotationDays { get; set; }
        public virtual DbSet<ProductQuotation> ProductQuotations { get; set; }
        public virtual DbSet<QuotationDay> QuotationDays { get; set; }
        public virtual DbSet<QuotationMaster> QuotationMasters { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<FunctionDetail> FunctionDetails { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
        public virtual DbSet<MenuUserAllocation> MenuUserAllocations { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<EnquiryFollowUp> EnquiryFollowUps { get; set; }
    }
}
