//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HJStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuMaster()
        {
            this.MenuUserAllocations = new HashSet<MenuUserAllocation>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public Nullable<double> DisplayOrder { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsForEmployee { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuUserAllocation> MenuUserAllocations { get; set; }
    }
}
